### ISSUE TITLE
HTML entities are limited

### ISSUE THREAD

**Issue by tehciolo** [lee-dohm/autocomplete-html-entities#1]
Hello @lee-dohm !

I stumbled upon your provider while looking for an autocomplete solution to help me author some text.
I would have liked for it to contain the entities found [here](https://www.typewolf.com/cheatsheet).

It was very easy to modify the plugin code to add some that I needed and I thought that I may as well make a pull request to add them to the plugin repo. Would that be something you are interested in?

Cheers!

**Comment by lee-dohm** [comment]
Yes, please feel free to submit a PR :grinning:
